### PR TITLE
Spec 1.4 Specify FPCSR is R/W in user mode

### PR DESCRIPTION
**Pull request by stffrdhrn**
This adds the changes to the architecture specification as described in proposal 17:
   https://openrisc.io/proposals/p17-user-mode-fpcsr

This does away with the requirement to have `sr[SUMRA]`.  This is now inline with other CPU architectures like MIPS and PopwerPC. 

This also allows control of FPCSR in userspace which is needed to support C Library API's like `fesetenv` and `fesetround`.  This could be done with syscall's but that would not be as efficient.

### Concerns

This is a change of the spec which would be hard to detect in software or in the OS.  If software is running on an OpenRISC core it would not know that P17 is implemented unless it tries to write the the FPCSR and check results by reading.

### CODE REVIEW

**Comment by stffrdhrn** [comment]
I have also added website updates in: https://github.com/openrisc/openrisc.github.io/pull/17

**Comment by stffrdhrn** [comment]
A mail was also posted to the mailing list for this: https://lists.librecores.org/pipermail/openrisc/2022-February/003743.html

**Comment by stffrdhrn** [comment]
We also need to include the Tininess proposal:
  - https://openrisc.io/proposals/p18-fpu-tininess

**Review by bandvig — APPROVED** [review]
looks good

**Comment by stffrdhrn** [comment]
Thanks @bandvig , I will give a few more days for comments and merge this at the end of the week.

**Pull request merged**
